### ISSUE TITLE
Demo: Scroll does not work if input is focused and mouse over input- Firefox ESR

### ISSUE THREAD

**Issue by i5heu** [dosyago/dumbass#74]
If i focus the input and place my mouse over the input the scroll to control the number dose not work.

https://codepen.io/dosycorp/full/OJPQQzB

Firefox ESR 68.8.0esr (64-Bit)
Debian GNU/Linux 10 (buster)

**Comment by cris691** [comment]
Thanks for the report. I'll look into it.

**Comment by cris691** [comment]
Had a look in FF ESR and latest Chrome stable. This seems consistent.

**Comment by cris691** [comment]
The problem was:

```js
const spin = e => {
        e.deltaY > 0 ? inc() : dec();
        Spin(state);
      };
```

I was incrementing if `deltaY` was greater than zero (*down* the page), but actually, the browser behavior is to *decrement* the counter when a scroll happens *down* the page, and increment the input value when a scroll happens up the page.

Because I was doing the equal and opposite action of the browser behavior, when the input was focused, the two changes were occurring in opposite directions, an increment and a decrement, and canceling each other out. 

First I added a line to do not behavior if the input was focused:

```js
const spin = e => {
        if ( document.activeElement == e.target ) return;
        e.deltaY > 0 ?  inc() : dec()
        Spin(state);
      };
```

At which point I discovered that the implemented behavior was opposite to the browser, so I swapped the branches for the `inc()` and `dec()` calls, resolving the issue in the demo. 

Again, thanks @i5heu for the useful report 😄
